# Generated by Django 4.2.1 on 2023-05-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='biogragia',
            new_name='biografia',
        ),
    ]
